<?php

use App\Lines;
use Illuminate\Database\Seeder;

class LineSeeder extends Seeder
{
    protected $linesData = [
        ['id_group' => 1, 'name' => '(01) Consomes'],
        ['id_group' => 1, 'name' => '(02) Especias'],
        ['id_group' => 1, 'name' => '(03) Pure'],
        ['id_group' => 1, 'name' => '(04) Salsas'],
        ['id_group' => 1, 'name' => '(05) Mayonesa'],
        ['id_group' => 1, 'name' => '(06) Vinagres'],
        ['id_group' => 1, 'name' => '(07) Moles'],
        ['id_group' => 1, 'name' => '(08) Sal'],
        ['id_group' => 2, 'name' => '(01) Lenteja'],
        ['id_group' => 2, 'name' => '(02) Frijol'],
        ['id_group' => 2, 'name' => '(03) Arroz'],
        ['id_group' => 2, 'name' => '(04) Maiz palomero'],
        ['id_group' => 3, 'name' => '(01) Feculas'],
        ['id_group' => 3, 'name' => '(05) Harina de Maiz'],
        ['id_group' => 3, 'name' => '(06) Harina de Trigo'],
        ['id_group' => 3, 'name' => '(07) Harina de Hot Cakes'],
        ['id_group' => 4, 'name' => '(01) Atun'],
        ['id_group' => 4, 'name' => '(02) Chiles'],
        ['id_group' => 4, 'name' => '(03) Frijol'],
        ['id_group' => 4, 'name' => '(04) Vegetales'],
        ['id_group' => 4, 'name' => '(05) Almibares'],
        ['id_group' => 4, 'name' => '(07) Sardina'],
        ['id_group' => 4, 'name' => '(08) Chilorio'],
        ['id_group' => 5, 'name' => '(01) Pan Comercial'],
        ['id_group' => 5, 'name' => '(02) Pan Dulce'],
        ['id_group' => 5, 'name' => '(03) Pan Fresco'],
        ['id_group' => 5, 'name' => '(04) Cafe'],
        ['id_group' => 5, 'name' => '(05) Te'],
        ['id_group' => 5, 'name' => '(07) Modificadores'],
        ['id_group' => 5, 'name' => '(08) Cereales'],
        ['id_group' => 5, 'name' => '(09) Mermeladas Jaleas'],
        ['id_group' => 6, 'name' => '(01) Alimento Infantil'],
        ['id_group' => 6, 'name' => '(02) Panales'],
        ['id_group' => 6, 'name' => '(03) Articulos Bebes'],
        ['id_group' => 6, 'name' => '(04) Limpieza Bebes'],
        ['id_group' => 7, 'name' => '(02) Bebidas refrescantes'],
        ['id_group' => 7, 'name' => '(03) Cerveza'],
        ['id_group' => 7, 'name' => '(04) Concentrados'],
        ['id_group' => 7, 'name' => '(05) Jugos y Nectares'],
        ['id_group' => 7, 'name' => '(06) Refrescos'],
        ['id_group' => 7, 'name' => '(07) Bebidas Alcoholicas'],
        ['id_group' => 7, 'name' => '(08) Bebidas Infantiles'],
        ['id_group' => 7, 'name' => '(09) Energetica Isotonica'],
        ['id_group' => 7, 'name' => '(10) Aguas Saborizadas'],
        ['id_group' => 7, 'name' => '(11) Tes'],
        ['id_group' => 8, 'name' => '(01) Cacahuate'],
        ['id_group' => 8, 'name' => '(02) Mueganos'],
        ['id_group' => 8, 'name' => '(03) Frituras'],
        ['id_group' => 8, 'name' => '(04) Palomitas'],
        ['id_group' => 9, 'name' => '(01) Chocolate'],
        ['id_group' => 9, 'name' => '(02) Dulces'],
        ['id_group' => 9, 'name' => '(03) Goma de Mascar'],
        ['id_group' => 9, 'name' => '(04) Malvaviscos'],
        ['id_group' => 9, 'name' => '(06) Tamarindos'],
        ['id_group' => 9, 'name' => '(07) Tradicionales'],
        ['id_group' => 10, 'name' => '(06) Yoghurt'],
        ['id_group' => 11, 'name' => '(01) Afeitado'],
        ['id_group' => 11, 'name' => '(02) Higiene Bucal'],
        ['id_group' => 11, 'name' => '(03) Higiene Fem'],
        ['id_group' => 11, 'name' => '(04) Jabones'],
        ['id_group' => 11, 'name' => '(05) Shampoo'],
        ['id_group' => 11, 'name' => '(06) Cremas'],
        ['id_group' => 11, 'name' => '(07) Desodorantes'],
        ['id_group' => 11, 'name' => '(09) Fijadores'],
        ['id_group' => 11, 'name' => '(12) Cuidado Facial'],
        ['id_group' => 11, 'name' => '(13) Solares'],
        ['id_group' => 11, 'name' => '(14) Coloracion'],
        ['id_group' => 11, 'name' => '(15) Cosmeticos'],
        ['id_group' => 12, 'name' => '(01) Higienico'],
        ['id_group' => 12, 'name' => '(02) Servilletas'],
        ['id_group' => 13, 'name' => '(01) Jabon Ropa'],
        ['id_group' => 13, 'name' => '(02) Lavatrastes liquido'],
        ['id_group' => 13, 'name' => '(03) Limpiadores'],
        ['id_group' => 13, 'name' => '(04) Suavizantes'],
        ['id_group' => 13, 'name' => '(05) Pastillas'],
        ['id_group' => 13, 'name' => '(06) Blanqueadores'],
        ['id_group' => 13, 'name' => '(07) Detergente Liq'],
        ['id_group' => 13, 'name' => '(08) Detergente Polvo'],
        ['id_group' => 13, 'name' => '(09) Detergente Multi'],
        ['id_group' => 13, 'name' => '(10) Lavatrastes Polvo'],
        ['id_group' => 14, 'name' => '(01) Desechables'],
        ['id_group' => 14, 'name' => '(03) Velas Veladoras'],
        ['id_group' => 14, 'name' => '(04) Focos'],
        ['id_group' => 14, 'name' => '(06) Articulos Limpieza'],
        ['id_group' => 14, 'name' => '(07) Insect Aroma'],
        ['id_group' => 14, 'name' => '(14) Aluminio'],
        ['id_group' => 14, 'name' => '(16) Ceras'],
        ['id_group' => 14, 'name' => '(17) Cigarros'],
        ['id_group' => 14, 'name' => '(19) Pilas'],
        ['id_group' => 14, 'name' => '(20) Tarjeta Regalo'],
        ['id_group' => 15, 'name' => '(01) Recargas'],
        ['id_group' => 15, 'name' => '(03) Pago de Servicios'],
        ['id_group' => 15, 'name' => '(04) Comisiones'],
        ['id_group' => 16, 'name' => '(01) Flan'],
        ['id_group' => 16, 'name' => '(02) Gelatinas'],
        ['id_group' => 17, 'name' => '(01) Pastas'],
        ['id_group' => 17, 'name' => '(02) Instantaneas'],
        ['id_group' => 18, 'name' => '(01) Hielo'],
        ['id_group' => 19, 'name' => '(01) Farmacia'],
        ['id_group' => 19, 'name' => '(02) Farmacia OTC'],
        ['id_group' => 19, 'name' => '(03) Curacion'],
        ['id_group' => 19, 'name' => '(04) Panales Adulto'],
        ['id_group' => 20, 'name' => '(01) Soya'],
        ['id_group' => 20, 'name' => '(02) Mixto'],
        ['id_group' => 20, 'name' => '(03) Canola'],
        ['id_group' => 20, 'name' => '(04) Palma'],
        ['id_group' => 21, 'name' => '(01) Saladas'],
        ['id_group' => 21, 'name' => '(02) Dulces'],
        ['id_group' => 22, 'name' => '(01) Alimentos Congelados'],
        ['id_group' => 22, 'name' => '(02) Postre Congelado'],
        ['id_group' => 23, 'name' => '(01) Bolsas'],
        ['id_group' => 24, 'name' => '(V1) In&Out'],
        ['id_group' => 25, 'name' => '(01) ID'],
        ['id_group' => 26, 'name' => '(01) Estandar'],
        ['id_group' => 27, 'name' => '(01) Alimento Seco'],
        ['id_group' => 27, 'name' => '(02) Alimento Humedo'],
        ['id_group' => 27, 'name' => '(03) Premios'],
        ['id_group' => 27, 'name' => '(04) Accesorios'],
        ['id_group' => 28, 'name' => '(02) Leches'],
        ['id_group' => 28, 'name' => '(03) Leches enlatadas'],
        ['id_group' => 28, 'name' => '(04) Leches en polvo'],
        ['id_group' => 29, 'name' => '(01) Crema'],
        ['id_group' => 29, 'name' => '(02) Mantequilla Margarin'],
        ['id_group' => 29, 'name' => '(03) Quesos'],
        ['id_group' => 29, 'name' => '(04) Yoghurt'],
        ['id_group' => 29, 'name' => '(05) Postres Refrigerados'],
        ['id_group' => 29, 'name' => '(06) Leches'],
        ['id_group' => 29, 'name' => '(07) Bebidas Fermentadas'],
        ['id_group' => 29, 'name' => '(08) Infantil'],
        ['id_group' => 30, 'name' => '(01) Carnes Frias'],
        ['id_group' => 30, 'name' => '(02) Alimentos Preparados'],
        ['id_group' => 31, 'name' => '(1) Close Out'],
        ['id_group' => 31, 'name' => '(2) Temporada'],
        ['id_group' => 32, 'name' => '(01) Tortillas'],
        ['id_group' => 32, 'name' => '(02) Tostadas'],
        ['id_group' => 33, 'name' => '(01) Agua Natural'],
        ['id_group' => 33, 'name' => '(02) Agua Mineral'],
        ['id_group' => 34, 'name' => '(01) Blanco'],
        ['id_group' => 34, 'name' => '(02) Organico'],
        ['id_group' => 2, 'name' => '(99) Varios'],
        ['id_group' => 4, 'name' => '(99) Varios'],
        ['id_group' => 5, 'name' => '(99) Varios'],
        ['id_group' => 7, 'name' => '(01) Aguas'],
        ['id_group' => 7, 'name' => '(99) Varios'],
        ['id_group' => 8, 'name' => '(05) Tostadas'],
        ['id_group' => 9, 'name' => '(99) Varios'],
        ['id_group' => 10, 'name' => '(01) Huevo'],
        ['id_group' => 10, 'name' => '(02) Mantequilla Margarina'],
        ['id_group' => 10, 'name' => '(05) Quesos'],
        ['id_group' => 10, 'name' => '(07) Postres Refrigerados'],
        ['id_group' => 11, 'name' => '(08) Belleza'],
        ['id_group' => 11, 'name' => '(11) Panales Adulto'],
        ['id_group' => 14, 'name' => '(99) Varios'],
        ['id_group' => 20, 'name' => '(99) Varios'],
        ['id_group' => 28, 'name' => '(01) Huevo'],
        ['id_group' => 29, 'name' => '(01) Huevo'],
        ['id_group' => 29, 'name' => '(05) Quesos'],
        ['id_group' => 16, 'name' => '(07) Postres Refrigerados'],
        ['id_group' => 26, 'name' => '(99) Varios']
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->linesData as $item) {
            Lines::create($item);
        }
    }
}
